apiVersion: v1
kind: Service
metadata:
  name: signed-image-webhook
  namespace: security
  labels:
    app: signed-image-webhook
spec:
  selector:
    app: signed-image-webhook
  ports:
    - name: https
      port: 443
      targetPort: 8443
